### ISSUE TITLE
add assertions 

### ISSUE THREAD

**Issue by chrissmeets31** [johanverh/Fontys-SWE-Wk4-5#10]
Add assertions see orcacle $ sheets

**Comment by johanverh** [comment]
If = engels de rest is nederlands....

BeeFreezPas.java
betaal
Ik mis pre en post
If tank limiet is bereikt is > Maximum liters overschreden (misschien exception ook hernoemen)
If het saldo niet negatief is > Saldo mag niet negatief worden
If het kreditielimiet is bereikt is > Kreditelimiet bereikt
if het maximum bereikt is > Maximum bedrag overschreden

spaar 
ik mis pre en post

Return waarde staat nog ter discussie

Credit.java
Ok

Kleingeld.java 

constructor1:
{@inheritDoc }?
naam van de pahouder > naam van de pashouder

construcor2:
{@inheritDoc }? > bij constructor?
 parameter niet uitgeschreven

Betaal:
 combinatie van {@inheritDoc } en ...

Normaal.java
Constructor1:
Andere schrijfwijze als de rest. Consitentie!

Spaar:
Hoe zou je het probleem oplossen het maximum aantal liters per pas verschillende zou zijn?
Is het misschien een idee om het maximumLitersPerTankbeurt in de constructor mee te geven. Vindt ik een netter en beters OOP oplossing. Wat vindt jij? Foutmelding moet dan ook gewijzigd worden...

Betaal:
 throws alleen de SaldoNietNegatiefException. De rest is hier niet van toepassing.


Ik hoop dat je iets aan mijn feedback hebt.
